# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/.yaml-lint.yml

---

extends: default

yaml-files:
  - '*.yml'

rules:
  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.line_length
  line-length:
    max: 180

  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy
  truthy:
    allowed-values: [
      'true',
      'false'
    ]
    check-keys: true
