---

extends: default

yaml-files:
  - '*.yml'

rules:
  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.line_length
  line-length:
    max: 180

  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy
  truthy:
    allowed-values: [
      'true',
      'false'
    ]
    check-keys: true
